#!/bin/sh
set -eu

#DEBHELPER#

case "$1" in
    purge)
      rm -rf /var/lib/rspamd
      rm -rf /var/log/rspamd
      rm -rf /run/rspamd
    ;;

    remove|upgrade|disappear|failed-upgrade|abort-*)
    ;;

    *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
    ;;
esac
